#示例配置信息

#其他配置文件,可以使用绝对路径
#或者相对于 anylink 二进制文件的路径

#数据文件
db_type = "sqlite3"
db_source = "./conf/anylink.db"
#证书文件
cert_file = "./conf/vpn_cert.crt"
cert_key = "./conf/vpn_cert.key"
files_path = "./conf/files"
log_level = "debug"

#系统名称
issuer = "XLXXVPN"
#后台管理用户
admin_user = "admin"
#pass 123456
#admin_pass = "$2a$10$UQ7C.EoPifDeJh6d8.31TeSPQU7hM/NOM2nixmBucJpAuXDQNqNke"
admin_pass = "$2a$10$pHI9aUm/GMfGMk/FHNbxX.aAjIxUyxWYuiHiJIkiDLGty.qUYBwrC"
jwt_secret = "_8ikcgHXfiwDagK39OjdSTTwZ3hO6oSAO5ZxOKJJiSkHwcl-ujfjtL5s"

#服务监听地址
server_addr = ":1234"
#后台服务监听地址
admin_addr = ":8800"


#客户端分配的ip地址池
ipv4_master = "br-lan"
ipv4_cidr = "192.168.99.0/24"
ipv4_gateway = "192.168.99.1"
ipv4_start = "192.168.99.10"
ipv4_end = "192.168.99.250"

#是否自动添加nat
iptables_nat = true


#客户端显示详细错误信息(线上环境慎开启)
display_error = false


